---
title: "Ways of Comparing Models"
author: "Katie Renwick"
date: "August 19, 2016"
output: pdf_document
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE, include=F}
rm(list=ls())
library(dplyr)
library(tidyr)
library(ggplot2); theme_set(theme_bw(base_size=20)) # sized for ppt
library(gridExtra)
library(wesanderson)
library(splines)
library(data.table)
library(knitr)
library(GGally)

# set file path for sageseer- CHANGE BASED ON YOUR COMPUTER
#setwd("/Users/poulterlab1/version-control/sageseer/")

# folder path:
dpath <- "/Users/poulterlab1/version-control/sageseer/data/"
opath <- "/Users/poulterlab1/version-control/sageseer/figures/"

# Pull in merged data and manipulate
merged <- read.csv(paste(dpath, "merged_data_perturb.csv", sep=""))
m3 <- merged %>%
  mutate(change=predicted-baseline) %>%
  mutate(direction=ifelse(change>0,"Positive","Negative")) %>%
  na.omit() %>%
  dplyr::select(site:climate,change) 
m3 %>% group_by(model) %>% summarise(mbase=mean(baseline),mpred=mean(predicted))
```

Pairwise comparison of predicted baseline: simple correlation matrix.
```{r, echo = F, fig.width = 14, fig.height = 10,  results='asis',message=F}
# Plot baseline + change for each model compared to each other model
d <- dplyr::filter(m3, mag==4 & var=="temp") %>%
  dplyr::select(site,model,baseline,climate) %>%
  spread(model,baseline) %>%
  na.omit()
#pairs(d[,3:6])
kable(cor(d[,3:6],use="complete"),digits=2)
```

Pairwise comparison of predicted with 4c temp increase: simple correlation matrix.
```{r, echo = F, fig.width = 14, fig.height = 10,  results='asis',message=F}
# Plot baseline + change for each model compared to each other model
d <- dplyr::filter(m3, mag==4 & var=="temp") %>%
  dplyr::select(site,model,predicted,climate) %>%
  spread(model,predicted)
#pairs(d[,3:6])
kable(cor(d[,3:6],use="complete"),digits=2)
```

Pairwise comparison of change (predicted-baseline), 4C temp increase.
```{r, echo = F, fig.width = 14, fig.height = 10,  results='asis',message=F}
# Plot baseline + change for each model compared to each other model
d <- dplyr::filter(m3, mag==4 & var=="temp") %>%
  dplyr::select(site,model,change,climate) %>%
  spread(model,change)
#pairs(d[,3:6])
kable(cor(d[,3:6],use="complete"),digits=2)
```

Pairwise comparison of change (predicted-baseline), 4C temp increase.

```{r, echo = F, fig.width = 4, fig.height = 4,  results='asis',message=F}
# Plot baseline + change for each model compared to each other model
d <- dplyr::filter(m3, mag==4 & var=="temp") %>%
  dplyr::select(site,model,change,climate) %>%
  spread(model,change)
#pairs(d[,3:6])
ggcorr(d[,3:6])
```

```{r, echo = F, fig.width = 8.5, fig.height = 11,  results='asis',message=F}
#ggpairs(d[,2:6],
        #mapping = ggplot2::aes(color = climate))
```

```{r, echo = F, fig.width = 14, fig.height = 10,  results='asis',message=F}
ggplot(data=d, aes(x=randfor,y=`DGVM-full-400ppm`)) +
    geom_point(aes(color=climate)) +
    geom_hline(yintercept=0, linetype="dashed") +
    geom_vline(xintercept=0, linetype="dashed") +
    geom_smooth(method="lm") +
  stat_ellipse()
ggplot(data=d, aes(x=randfor,y=DRS)) +
  geom_point(aes(color=climate)) +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_smooth(method="lm")
ggplot(data=d, aes(x=`DGVM-full-400ppm`,y=DRS)) +
  geom_point(aes(color=climate)) +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_smooth(method="lm")
ggplot(data=d, aes(x=`DGVM-full-400ppm`,y=AK)) +
  geom_point(aes(color=climate)) +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_smooth(method="lm")
ggplot(data=d, aes(x=randfor,y=AK)) +
  geom_point(aes(color=climate)) +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_smooth(method="lm")
ggplot(data=d, aes(x=DRS,y=AK)) +
  geom_point(aes(color=climate)) +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_smooth(method="lm")
```

